const item = [
  {
    id: 1,
    img: "https://www.ikea.com/sg/en/images/products/bekant-desk-sit-stand-white-stained-oak-veneer-white__0857099_pe714391_s5.jpg?f=sg",
    brand: "BEKANT",
    name: "Desk sit/stand, white stained oak veneer/white160x80 cm",
    desc: "This sturdy desk is guaranteed to outlast years of coffee and hard work. You get a generous work surface and a clever solution to keep cables in place underneath.",
    price: 799,
    category: "Home office",
  },
  {
    id: 2,
    img: "https://www.ikea.com/sg/en/images/products/hattefjaell-office-chair-with-armrests-gunnared-beige-white__0724647_pe734547_s5.jpg?f=sg",
    brand: "HATTEFJÄLL",
    name: "Office chair with armrests, Gunnared beige/white",
    desc: "The gently curved lines accentuated by sewn details are kind to your body and pleasant to look at. Also, there’s a tilt and height-adjusting mechanism that’s built to outlast years of ups and downs.",
    price: 379,
    category: "Home office",
  },
  {
    id: 3,
    img: "https://www.ikea.com/sg/en/images/products/tjena-desk-organiser-white__0910640_pe667300_s5.jpg?f=sg",
    brand: "TJENA",
    name: "Desk organiser, white18x17 cm",
    desc: "The desk organiser is perfect for storing all kinds of small things – and since the 5 boxes are loose, you can move and place them in the way that suits you and your things best.",
    price: 7.9,
    category: "Home office",
  },
  {
    id: 4,
    img: "https://www.ikea.com/sg/en/images/products/micke-desk-white__0736022_pe740349_s5.jpg?f=sg",
    brand: "MICKE",
    name: "Desk, white73x50 cm",
    desc: "A clean and simple look that fits just about anywhere. You can combine it with other desks or drawer units in the MICKE series to extend your work space. The clever design at the back hides messy cables.",
    price: 89,
    category: "Home office",
  },
  {
    id: 5,
    img: "https://www.ikea.com/sg/en/images/products/bekant-shelving-unit-white__0612867_pe686066_s5.jpg?f=sg",
    brand: "BEKANT",
    name: "Shelving unit, white121x134 cm",
    desc: "Suitable as a room divider as it has the same finish on the back and looks good from all sides.",
    price: 429,
    category: "Home office",
  },
  {
    id: 6,
    img: "https://www.ikea.com/sg/en/images/products/aengslilja-duvet-cover-and-2-pillowcases-grey__0642512_pe701209_s5.jpg?f=sg",
    brand: "ÄNGSLILJA",
    name: "Desk organiser, white18x17 cm",
    desc: "ÄNGSLILJA duvet cover adds a casual and relaxed air to you bedroom. The washed cotton fabric gives harmonius colours and feels as soft as it looks so you can wake up feeling fresh and well-rested.",
    price: 39.9,
    category: "Bedroom",
  },
  {
    id: 7,
    img: "https://www.ikea.com/sg/en/images/products/hauga-upholstered-bed-frame-vissle-grey__0789232_pe764315_s5.jpg?f=sg",
    brand: "HAUGA",
    name: "Upholstered bed frame, Vissle grey150x200 cm",
    desc: "This upholstered bed frame brings warmth and softness into your bedroom. The durable two-toned fabric, the gently curved headboard and the piped edges create a classic expression you will enjoy for years.",
    price: 399,
    category: "Bedroom",
  },
  {
    id: 8,
    img: "https://www.ikea.com/sg/en/images/products/klubbsporre-ergonomic-pillow-multi-position__0792296_pe764700_s5.jpg?f=sg",
    brand: "KLUBBSPORRE",
    name: "Ergonomic pillow, multi position41x70 cm",
    desc: "This ergonomic pillow is made of memory foam topped with a gel layer that gives you a cool, soothing sleep surface. This means you sleep comfortably all night without waking up feeling hot and clammy.",
    price: 59,
    category: "Bedroom",
  },
  {
    id: 9,
    img: "https://www.ikea.com/sg/en/images/products/malm-bed-frame-high-w-4-storage-boxes-black-brown-luroey__0637597_pe698414_s5.jpg?f=sg",
    brand: "MALM",
    name: "Bed frame, high, w 4 storage boxes, black-brown/Luröy180x200 cm",
    desc: "A clean design with solid wood veneer. Place the bed freestanding or with the headboard against a wall. You also get spacious storage boxes that roll out smoothly on castors.",
    price: 599,
    category: "Bedroom",
  },
  {
    id: 10,
    img: "https://www.ikea.com/sg/en/images/products/hoevag-pocket-sprung-mattress-firm-dark-grey__0210701_pe364283_s5.jpg?f=sg",
    brand: "HÖVÅG",
    name: "Pocket sprung mattress, firm/dark grey150x200 cm",
    desc: "The pocket springs act independently to follow the contours and movements of your body. Add to this, a thick layer of soft filling for even more luxury and comfort.",
    price: 499,
    category: "Bedroom",
  },
  {
    id: 11,
    img: "https://www.ikea.com/sg/en/images/products/friheten-corner-sofa-bed-with-storage-hyllie-dark-grey__0690261_pe723182_s5.jpg?f=sg",
    brand: "FRIHETEN",
    name: "Corner sofa-bed with storage, Hyllie dark grey",
    desc: "After a good night’s sleep, you can effortlessly convert your bedroom or guest room into a living room again. The built-in storage is easy to access and spacious enough to stow bedding, books and PJs.",
    price: 890,
    category: "Living room",
  },
  {
    id: 12,
    img: "https://www.ikea.com/sg/en/images/products/strandmon-wing-chair-djuparp-dark-green__0531313_pe647261_s5.jpg?f=sg",
    brand: "STRANDMON",
    name: "Wing chair, Djuparp dark green",
    desc: "Need a hug? STRANDMON wing chair has an embracing feel with a high back, round armrests, soft lines and inviting upholstery. A traditional look with modern comfort for many cosy moments.",
    price: 299,
    category: "Living room",
  },
  {
    id: 13,
    img: "https://www.ikea.com/sg/en/images/products/bergshult-sandshult-wall-shelf-brown-black-white-stained-aspen__0789938_pe764241_s5.jpg?f=sg",
    brand: "BERGSHULT / SANDSHULT",
    name: "Wall shelf, brown-black/white stained aspen120x30 cm",
    desc: "With this wall shelf, you can use your empty walls to display your things. Use it in the bedroom, as a sideboard in the living room, a display shelf by the dining table – or whatever you decide.",
    price: 30.9,
    category: "Living room",
  },
  {
    id: 14,
    img: "https://www.ikea.com/sg/en/images/products/beraekna-vase-clear-glass__0639834_pe699599_s5.jpg?f=sg",
    brand: "BERÄKNA",
    name: "Vase, clear glass45 cm",
    desc: "The large vase is mouth blown by a skilled glassblower who has developed the art of creating finished glass products over many years. The size gives the vase character and makes it a real eye-catcher.",
    price: 34.9,
    category: "Living room",
  },
  {
    id: 15,
    img: "https://www.ikea.com/sg/en/images/products/knoxhult-kitchen-wood-effect-grey__0767715_pe754202_s5.jpg?f=sg",
    brand: "KNOXHULT",
    name: "Kitchen, wood effect grey204x61x220 cm",
    desc: "Just right if you want a small kitchen with a portable hob and all necessary basic storage. As fast and easy to buy as to start using, since we’ve combined the modules into a ready-made solution.",
    price: 519,
    category: "Kitchen",
  },
  {
    id: 16,
    img: "https://www.ikea.com/sg/en/images/products/tillreda-fridge-white__0461681_pe607731_s5.jpg?f=sg",
    brand: "TILLREDA",
    name: "Fridge, white45 l",
    desc: "A small fridge for a small-sized kitchen. Also handy in the den, basement, guest house, dorm room or wherever you may want quick access to a beverage or snack.",
    price: 149,
    category: "Kitchen",
  },
  {
    id: 17,
    img: "https://www.ikea.com/sg/en/images/products/tillreda-portable-induction-hob-white__0529064_pe646069_s5.jpg?f=sg",
    brand: "TILLREDA",
    name: "Portable induction hob, white",
    desc: "It’s perfect for smaller kitchens or wherever you need an extra cooking zone. It’s easy to move around and can be stowed away when not in use to free up counter space for other activities.",
    price: 79,
    category: "Kitchen",
  },
  {
    id: 18,
    img: "https://www.ikea.com/sg/en/images/products/vadholma-rack-for-kitchen-island-black__0870713_pe683472_s5.jpg?f=sg",
    brand: "VADHOLMA",
    name: "Rack for kitchen island, black",
    desc: "Gives you extra storage in your kitchen.",
    price: 130,
    category: "Kitchen",
  },
  {
    id: 19,
    img: "https://www.ikea.com/sg/en/images/products/godmorgon-odensvik-bathroom-furniture-set-of-4-white-stained-oak-effect-dalskaer-tap__0730962_pe737886_s5.jpg?f=sg",
    brand: "GODMORGON / ODENSVIK",
    name: "Bathroom furniture, set of 4, white stained oak effect/Dalskär tap103 cm",
    desc: "The light wooden expression with visible grain pattern brings a warm glow to your bathroom. The clever mirror cabinet also has mirrors on the inside so you can check your hair at different angles!",
    price: 1160,
    category: "Bathroom",
  },
  {
    id: 20,
    img: "https://www.ikea.com/sg/en/images/products/storjorm-mirror-cab-2-door-built-in-lighting-white__0863687_pe555097_s5.jpg?f=sg",
    brand: "STORJORM",
    name: "Mirror cab 2 door/built-in lighting, white100x14x96 cm",
    desc: "The LED lightsource consumes up to 85% less energy and lasts 20 times longer than incandescent bulbs.",
    price: 545,
    category: "Bathroom",
  },
];

export default item;
